"""empty message

Revision ID: 24099bbf636b
Revises: 8dd8b0230d98
Create Date: 2025-05-06 17:11:25.390956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24099bbf636b'
down_revision = '8dd8b0230d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=60), nullable=False))
        batch_op.drop_column('height')
        batch_op.drop_column('gender')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrian', sa.String(length=60), nullable=False))
        batch_op.drop_column('gravity')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('terrian')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eye_color')

    # ### end Alembic commands ###
